---
title: "Risk of acute conditions partially-attributable to alcohol"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Alcohol partially-attributable acute risk}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: disease-risks.bib
link-citations: yes
citation_package: natbib
biblio-style: vancouver
urlcolor: blue
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction
Here we describe the approach taken in STAPM to model the health harms that are partially-attributable to level of acute alcohol intake on a single occasion (i.e. intoxication). The health harms that we consider could be intentional or unintentional, e.g. traffic accidents, assault or falls. "Partially-attributable acute" means that the harm can occur without alcohol but the risk of occurrence changes with intoxication.    

The Health Survey for England (HSE) data provide the basis for our analysis (see the [hseclean R package](https://stapm.gitlab.io/hseclean/) for details of how we process the HSE data).   

We build on the method used to model the health harms due to intoxication in the Sheffield Alcohol Policy Model (SAPM). The methods used for this module of SAPM have evolved over time. Originally, the risk of harm was inferred from external information on the alcohol attributable fractions of traffic accidents, assaults, falls etc (described in the Purshouse et al. modelling report for NICE [-@purshouse2009nice]). The method was updated to allow SAPM to model individual exposure to the risk of harm from each drinking occassion, e.g. for how long is someone intoxicated after drinking and what is their risk of a fall injury when intoxicated -- this new method is described in two papers by Hill-McManus et al. [-@hill2014estimation;-@Hill-McManus2014]. Most recently, the method was updated to incorporate new estimates of the risk of health harms due to intoxication by Cherpitel et al. [-@cherpitel2015relative] -- these are described in our alcohol risk functions report [@Angus2018] and we have used them in our [alcohol attributable fractions report](https://figshare.shef.ac.uk/articles/Alcohol_attributable_fractions_for_England/8181845).    

In this vignette, we first describe the latest SAPM method for modelling the health harms due to intoxication, and then describe how we adapt the method to suit STAPM.   

# The latest SAPM method

## Number of drinking occassions
The first step is to estimate the number of drinking occassions that an individual has in a year and we have two sources of information on this.   

The HSE asks repondents about the frequency they drank alcoholic drinks in the last 12 months (in the variable `dnoft`), offering the responses: Almost every day, Five or six days a week, Three or four days a week, Once or twice a week, Once or twice a month, Once every couple of months, Once or twice a year. For interval frequencies, we take the mid point value. We convert yearly frequencies to weekly frequency. For example, Three or four days a week becomes 3.5 times a week. This processing is done by the function `hseclean::alc_drink_now_allages()` that calls the function `hseclean::alc_drink_freq()`.      

Hill-McManus et al. [-@hill2014estimation] developed a method to estimate the number of drinking occassions per year using data from detailed diaries in the National Diet and Nutrition Survey (NDNS) 2000/2001. Using the regression coefficients from this study, it is possible to predict each individual's expected number of drinking occasions across the year, the average amount they drunk on an occasion, the variability in the amount drunk among occasions, and how these vary socio-demographically. Hill-McManus et al. use a negative binomial regression model for the number of weekly drinking occasions (see their Table 3). The explanatory variables for the number of weekly drinking occassions were: log weekly mean consumption, age, income (in poverty or not), ethnicity (white/non-white), age left education, number of children, social class (manual/nonmanual). From the regression coefficients we calculate the expected number of weekly drinking occasions for each individual in the HSE data (implemented in the STAPM code by the function `tobalcepi::AlcBinge()`). Note that this model was fitted to a population sample aged below 65 years, but we assume the effect at 55--65 years applies at older ages too.     

## Amount drunk on drinking occassions
The second step is to estimate the distribution of the amounts that each individual drinks on their drinking occassions. The HSE does not provide this information -- it asks questions on the number of units that each individual drank on their heaviest drinking day in the last seven days but this does not tell us about the distribution of amounts drunk across all drinking occassions in a year.    

SAPM uses the method developed by Hill-McManus et al. [-@hill2014estimation] -- there are two parts to the process of estimating the distribution of amount drunk.   

First, estimate the average quantity of alcohol that we expect each individual to consume on a drinking occasion. Hill-McManus et al. estimated regression coefficients (their Table 4) that allow predictions of the average amount consumed. The predictors of average amount consumed were: log weekly mean consumption, age, sex, ethnicity (non-white/white), and an interaction between sex and log weekly mean consumption (indicating that men and women differ in the number of drinking occassions required to achieve the same level of weekly consumption). Note that an estimate of the average quantity of alcohol consumed on a drinking occasion can also be obtained from the HSE data by dividing average weekly consumption by the number of weekly drinking occasions.    

Second, estimate the individual-level variability in the amount consumed across their drinking occassions. To do this, Hill-McManus et al. fitted two Heckman regression models to the NDNS data:   

*Model 1* was a Heckman selection model designed to correct the analysis for the problem that the NDNS data only provides a seven-day snapshot of each individual's annual drinking, and at least three data points per individual are needed to estimate the variability in amount drunk. The Heckman selection model estimated the probability that an individual drank on at least three separate occasions during the diary period (see their Table 5). The results were used to correct the estimates of variability for selection bias via the [Inverse Mills Ratio](https://en.wikipedia.org/wiki/Mills_ratio#Inverse_Mills_ratio). The predictors of an individual drinking on at least three separate occassions during the diary period were: log weekly mean consumption, age, income (in poverty or not), employed/not-employed, ethnicity (non-white/white), age left education, number of children, social class (manual/non-manual).    

*Model 2* was a Heckman outcome regression fitted to the standard deviation of the quantity of alcohol consumed in a drinking occasion (see their Table 6). The predictors of the standard deviation in the quantity of alcohol consumed in a drinking occasion were: log weekly mean consumption, income (in poverty or not), and the Inverse Mills ratio.    

In the STAPM code, the function `tobalcepi::AlcBinge()` uses the HSE data and the regression coefficients from Hill-McManus et al. to infer the mean and standard deviation of amount drunk on each drinking occassion by individuals who drink. From these two parameters, we then calculate individual-specific probability density functions of the amount of alcohol consumed on a drinking occasion (in the STAPM code, this is done within the function `tobalcepi::PArisk()`).   

## Time spent intoxicated
The third step is to estimate each individual's annual exposure to the risk of health harms due to intoxication, as defined by the amount of time that they spend intoxicated during a year (here we use 'intoxicated' to mean having a percentage blood alcohol content (\%BAC) greater than zero). The method that we use to estimate the time that each individual spends intoxicated over a year is described in Hill-McManus et al. [-@Hill-McManus2014], who drew on Taylor et al. [-@taylor2011combining].     

The expected duration of intoxication for each amount of alcohol drunk on an occassion is defined in terms of the time, in hours, after a drinking occassion that it would take for an individual's \%BAC to drop to zero. The calculation of this time considers:   

- an individual's sex, height and weight;   

- Widmark's $r$ (the fraction of the body mass in which alcohol would be present if it were distributed at concentrations equal to that in blood - see examples of use of the Widmark equation in Watson [-@watson1981prediction] and Posey and Mozayani [-@Posey2007]);   

- the rate at which the liver clears alcohol from the body (we assume this is 0.017 \%BAC per hour).   

To simplify the calculation, we do not consider the rate of alcohol absorbtion (i.e. there is no alcohol absorbtion rate constant) or the time interval between drinks within a drinking occassion.    

The calculation of the time that each individual spends intoxicated in a year multiplies the probability that each level of alcohol is consumed on a drinking occassion by the expected duration of intoxication for each amount of alcohol that could be drunk on an occassion. This is then multiplied by the expected number of drinking occasions per week and by 52 weeks in a year. Finally, the time spent intoxicated is summed to give the expected time spent intoxicated in a year (in the STAPM code, this is implemented by the function `tobalcepi::PArisk()`).     

## The annual relative risk of partially-attributable acute conditions
The relative risks for alcohol-related injuries are taken from Cherpitel et al. [-@cherpitel2015relative] and described in our alcohol risk functions report [@Angus2018]. Note that Cherpitel et al. report relative risks by the number of standard drinks consumed (we assume 1 Std. drink = 16ml (12.8g) of ethanol). The risk functions in Cherpital differ by four causes of health harm, which we map onto our disease list as follows:       

- Traffic   
- Violence: "Assault", "Other_intentional_injuries"   
- Falls  
- Other: "Mechanical_forces", "Drowning", "Other_unintentional_injuries", "intentional_self_harm", "Accidental_poisoning", "Fire_injuries".   

To calculate the annual relative risk for each condition, we do the following:   

- match each amount drunk on a drinking occassion to the associated relative risk (e.g. the relative risk of violence after a drinking occassion where 6 standard drinks were consumed);   

- multiply the relative risk associated with each drinking occassion by the expected amount of time spent intoxicated following that drinking occassion;    

- sum the relative risk associated with the time during the year that is spent intoxicated (the remaining time in the year that is not spent intoxicated has a relative risk of 1).   

The final estimate of each individual's annual relative risk of a partially-attributable acute condition is the average risk considering time spent intoxicated and time not spent intoxicated (in the STAPM code the calculations are implemented by the function `tobalcepi::PArisk()`).     

# Adaptation to suit STAPM
*The problem*  
STAPM uses a different method of modelling to SAPM in that STAPM tracks individuals as they age (the within-cohort dynamics) but SAPM does not -- instead SAPM models changes over time (in one-year time steps) to repeated cross-sectional samples of individuals from the HSE. The method described above is easily applied to a sample of individuals from the HSE (the SAPM method), because the HSE contains the necessary covariate (i.e. in the HSE sample there is also data on ethnicity, income, number of children etc.). For STAPM to use the method, would require it to also track the individual age trajectories of traits such as income -- and this is beyond the current scope of the STAPM modelling.    

*The solution*  
The STAPM modelling tracks the individual age trajectories of the average weekly amount of alcohol consumed -- the dynamics of these trajectories are stratified by sex and Index of Multiple Deprivation (IMD) quintiles. We therefore need to adapt the method to predict the number of drinking occassions and the distribution of amount consumed as a function of the average weekly amount of alcohol consumed, age, sex and IMD quintile. The simplest way to do this is to assign the parameter values from Hill-McManus et al. [-@hill2014estimation] to each individual in a sample of the HSE, and then to average these values by age, sex and IMD quintile (the IMD quintile averages will then reflect the variation among IMD quintiles in the distribution of ethnicity, income, number of children etc.).    

*Implementing in the STAPM code*   
The code to average the parameter values from Hill-McManus et al is in the folder `data-raw/binge_params` within the `tobalcepi` package. This code also averages individual height and weight by age, sex and IMD quintile, for use in the calculations of time spent intoxicated. A new function `tobalcepi::AlcBinge_stapm()` has been written to implement the calculations using these averaged parameter values. The functions `tobalcepi::RRAlc()` and `tobalcepi::PArisk()` have also had minor edits so that they work with the `tobalcepi::AlcBinge_stapm()` function.    

# References




